context:
  name: textual-autocomplete
  version: "4.0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name | replace("-", "_") }}/${{ name | replace("-", "_") }}-${{ version }}.tar.gz
  sha256: 3fcb353febbfc51063f84c673b26b0f427ff7bd457eb2fb006e35846213fdd2a

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - textual >=2.0.0,<3.0
    - typing-extensions >=4.5.0,<5.0

tests:
  - python:
      imports:
        - textual_autocomplete
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/darrenburns/textual-autocomplete
  summary: 'Easily add autocomplete dropdowns to your Textual apps.'
  description: |
    textual-autocomplete is a Python library for creating dropdown autocompletion menus in Textual applications, allowing users to quickly select from a list of suggestions as they type. textual-autocomplete supports Textual version 0.14.0 and above.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - claudiushaag
